var miserables = {
    nodes: [
        { id: "hep-ph", group: 166606 },
        { id: "math.CO", group: 56266 },
        { id: "cs.CG", group: 5851 },
        { id: "physics.gen-ph", group: 9829 },
        { id: "math.CA", group: 19726 },
        { id: "math.FA", group: 27020 },
        { id: "cond-mat.mes-hall", group: 80391 },
        { id: "gr-qc", group: 95612 },
        { id: "cond-mat.mtrl-sci", group: 79503 },
        { id: "astro-ph", group: 105380 },
        { id: "math.NT", group: 36094 },
        { id: "math.AG", group: 46658 },
        { id: "math.AT", group: 13608 },
        { id: "hep-th", group: 153175 },
        { id: "math.PR", group: 48639 },
        { id: "hep-ex", group: 48257 },
        { id: "nlin.PS", group: 8754 },
        { id: "physics.chem-ph", group: 18200 },
        { id: "q-bio.MN", group: 3374 },
        { id: "math.NA", group: 29950 },
        { id: "cond-mat.str-el", group: 65984 },
        { id: "cond-mat.stat-mech", group: 66650 },
        { id: "math.RA", group: 15179 },
        { id: "physics.optics", group: 38726 },
        { id: "physics.comp-ph", group: 18914 },
        { id: "q-bio.PE", group: 10096 },
        { id: "q-bio.CB", group: 1942 },
        { id: "quant-ph", group: 126854 },
        { id: "q-bio.QM", group: 8454 },
        { id: "hep-lat", group: 25820 },
        { id: "nucl-th", group: 52605 },
        { id: "math.OA", group: 11328 },
        { id: "math.QA", group: 17425 },
        { id: "math-ph", group: 71073 },
        { id: "math.MP", group: 71073 },
        { id: "nlin.CD", group: 14535 },
        { id: "physics.plasm-ph", group: 14029 },
        { id: "physics.space-ph", group: 5248 },
        { id: "nlin.SI", group: 10994 },
        { id: "cs.IT", group: 40171 },
        { id: "math.IT", group: 40171 },
        { id: "cs.NE", group: 11444 },
        { id: "cs.AI", group: 51133 },
        { id: "physics.ed-ph", group: 3311 },
        { id: "math.DG", group: 37441 },
        { id: "cond-mat.soft", group: 35471 },
        { id: "physics.pop-ph", group: 2175 },
        { id: "cs.DS", group: 20062 },
        { id: "math.CV", group: 15029 },
        { id: "math.DS", group: 31307 },
        { id: "physics.soc-ph", group: 19422 },
        { id: "nucl-ex", group: 23385 },
        { id: "math.RT", group: 22902 },
        { id: "cond-mat.other", group: 14692 },
        { id: "physics.flu-dyn", group: 22916 },
        { id: "physics.data-an", group: 9115 },
        { id: "cs.CE", group: 5226 },
        { id: "cs.MS", group: 1917 },
        { id: "cs.NA", group: 15954 },
        { id: "math.GR", group: 19376 },
        { id: "cond-mat.supr-con", group: 39516 },
        { id: "math.AC", group: 11324 },
        { id: "math.SG", group: 8107 },
        { id: "cs.CC", group: 9212 },
        { id: "math.KT", group: 5284 },
        { id: "math.GT", group: 20299 },
        { id: "math.AP", group: 52396 },
        { id: "physics.class-ph", group: 7690 },
        { id: "q-bio.OT", group: 1100 },
        { id: "physics.bio-ph", group: 13339 },
        { id: "q-bio.BM", group: 4629 },
        { id: "nlin.CG", group: 1390 },
        { id: "cs.DM", group: 11413 },
        { id: "cs.LO", group: 13552 },
        { id: "cond-mat.dis-nn", group: 21303 },
        { id: "math.MG", group: 9709 },
        { id: "physics.atom-ph", group: 18729 },
        { id: "math.SP", group: 8603 },
        { id: "math.ST", group: 19300 },
        { id: "stat.TH", group: 19300 },
        { id: "physics.ao-ph", group: 5190 },
        { id: "physics.ins-det", group: 18129 },
        { id: "q-fin.CP", group: 1886 },
        { id: "q-fin.PR", group: 1777 },
        { id: "physics.geo-ph", group: 5832 },
        { id: "q-bio.NC", group: 7765 },
        { id: "q-fin.RM", group: 1911 },
        { id: "q-bio.SC", group: 1581 },
        { id: "astro-ph.HE", group: 48404 },
        { id: "math.OC", group: 38033 },
        { id: "cs.CR", group: 23528 },
        { id: "math.CT", group: 7198 },
        { id: "math.LO", group: 11350 },
        { id: "cs.NI", group: 18338 },
        { id: "q-fin.GN", group: 2382 },
        { id: "q-fin.ST", group: 3076 },
        { id: "cs.LG", group: 118042 },
        { id: "cs.PF", group: 3178 },
        { id: "stat.ME", group: 20531 },
        { id: "stat.AP", group: 14800 },
        { id: "math.GM", group: 3442 },
        { id: "physics.atm-clus", group: 2486 },
        { id: "cs.SE", group: 11750 },
        { id: "physics.acc-ph", group: 6870 },
        { id: "math.GN", group: 4472 },
        { id: "stat.CO", group: 6765 },
        { id: "physics.hist-ph", group: 4340 },
        { id: "cs.AR", group: 3251 },
        { id: "cs.SC", group: 2131 },
        { id: "physics.med-ph", group: 5463 },
        { id: "stat.ML", group: 55692 },
        { id: "cs.CY", group: 13184 },
        { id: "cs.IR", group: 12203 },
        { id: "q-bio.GN", group: 2687 },
        { id: "cs.CV", group: 80984 },
        { id: "math.HO", group: 3129 },
        { id: "cs.OH", group: 2097 },
        { id: "cs.DB", group: 7001 },
        { id: "cs.DL", group: 4090 },
        { id: "cs.HC", group: 10823 },
        { id: "cs.PL", group: 6358 },
        { id: "nlin.AO", group: 6403 },
        { id: "cs.GT", group: 9024 },
        { id: "cs.DC", group: 16906 },
        { id: "cond-mat.quant-gas", group: 18508 },
        { id: "cs.MA", group: 5517 },
        { id: "cs.CL", group: 37430 },
        { id: "q-fin.PM", group: 1519 },
        { id: "cs.MM", group: 4408 },
        { id: "astro-ph.EP", group: 24176 },
        { id: "cs.RO", group: 20067 },
        { id: "econ.EM", group: 2484 },
        { id: "cs.ET", group: 3013 },
        { id: "q-bio.TO", group: 1918 },
        { id: "cs.GL", group: 187 },
        { id: "astro-ph.SR", group: 52375 },
        { id: "astro-ph.CO", group: 59643 },
        { id: "cs.FL", group: 4126 },
        { id: "cs.OS", group: 714 },
        { id: "q-fin.TR", group: 1467 },
        { id: "astro-ph.IM", group: 23880 },
        { id: "cs.SD", group: 9047 },
        { id: "cs.GR", group: 3959 },
        { id: "cs.SY", group: 22214 },
        { id: "astro-ph.GA", group: 53610 },
        { id: "cs.SI", group: 16336 },
        { id: "stat.OT", group: 1095 },
        { id: "physics.app-ph", group: 13419 },
        { id: "econ.TH", group: 1544 },
        { id: "econ.GN", group: 2577 },
        { id: "q-fin.EC", group: 3143 },
        { id: "eess.SY", group: 13775 },
        { id: "eess.IV", group: 15446 },
        { id: "eess.AS", group: 9017 },
        { id: "eess.SP", group: 18683 },
        { id: "q-fin.MF", group: 2014 },
        { id: "acc-phys", group: 49 },
        { id: "adap-org", group: 584 },
        { id: "q-bio", group: 1356 },
        { id: "cond-mat", group: 14215 },
        { id: "chao-dyn", group: 2398 },
        { id: "patt-sol", group: 650 },
        { id: "dg-ga", group: 732 },
        { id: "solv-int", group: 1413 },
        { id: "bayes-an", group: 16 },
        { id: "comp-gas", group: 221 },
        { id: "alg-geom", group: 1423 },
        { id: "funct-an", group: 427 },
        { id: "q-alg", group: 1578 },
        { id: "ao-sci", group: 17 },
        { id: "atom-ph", group: 123 },
        { id: "chem-ph", group: 251 },
        { id: "plasm-ph", group: 38 },
        { id: "mtrl-th", group: 262 },
        { id: "cmp-lg", group: 894 },
        { id: "supr-con", group: 175 },
    ],
    links: [
        { source: "solv-int", target: "math.NT", value: 4 },
        { source: "supr-con", target: "nlin.CD", value: 4 },
        { source: "astro-ph", target: "bayes-an", value: 6 },
        { source: "q-bio", target: "q-bio.NC", value: 6 },
        { source: "hep-ph", target: "acc-phys", value: 6 },
        { source: "astro-ph", target: "plasm-ph", value: 8 },
        { source: "chao-dyn", target: "ao-sci", value: 8 },
        { source: "cs.MA", target: "adap-org", value: 10 },
        { source: "cs.GL", target: "cs.LG", value: 16 },
        { source: "astro-ph", target: "atom-ph", value: 16 },
        { source: "gr-qc", target: "alg-geom", value: 20 },
        { source: "mtrl-th", target: "physics.chem-ph", value: 24 },
        { source: "ao-sci", target: "physics.ao-ph", value: 26 },
        { source: "bayes-an", target: "physics.data-an", value: 26 },
        { source: "atom-ph", target: "chem-ph", value: 42 },
        { source: "cs.OH", target: "cs.LG", value: 46 },
        { source: "cond-mat", target: "funct-an", value: 48 },
        { source: "cs.CY", target: "cs.GL", value: 54 },
        { source: "chao-dyn", target: "comp-gas", value: 54 },
        { source: "plasm-ph", target: "physics.plasm-ph", value: 56 },
        { source: "patt-sol", target: "solv-int", value: 58 },
        { source: "physics.space-ph", target: "math.MP", value: 64 },
        { source: "cs.AI", target: "cs.OH", value: 64 },
        { source: "acc-phys", target: "physics.acc-ph", value: 92 },
        { source: "q-bio.OT", target: "q-bio.QM", value: 94 },
        { source: "cs.AR", target: "cs.OS", value: 120 },
        { source: "math-ph", target: "math.GM", value: 136 },
        { source: "math.GM", target: "math.MP", value: 136 },
        { source: "astro-ph", target: "chao-dyn", value: 148 },
        { source: "q-alg", target: "solv-int", value: 150 },
        { source: "alg-geom", target: "dg-ga", value: 180 },
        { source: "nlin.CG", target: "physics.soc-ph", value: 200 },
        { source: "cond-mat", target: "supr-con", value: 204 },
        { source: "q-fin.RM", target: "q-fin.GN", value: 208 },
        { source: "econ.TH", target: "q-fin.EC", value: 214 },
        { source: "stat.OT", target: "stat.TH", value: 226 },
        { source: "cs.CY", target: "econ.GN", value: 232 },
        { source: "q-fin.CP", target: "q-fin.TR", value: 234 },
        { source: "chem-ph", target: "physics.chem-ph", value: 260 },
        { source: "q-fin.CP", target: "q-fin.PM", value: 264 },
        { source: "physics.bio-ph", target: "q-bio.OT", value: 268 },
        { source: "math.MG", target: "math.HO", value: 280 },
        { source: "cs.OS", target: "cs.DC", value: 320 },
        { source: "stat.ML", target: "q-bio.GN", value: 328 },
        { source: "cond-mat.mtrl-sci", target: "mtrl-th", value: 332 },
        { source: "q-fin.PR", target: "q-fin.RM", value: 338 },
        { source: "q-fin.EC", target: "stat.AP", value: 344 },
        { source: "q-bio.CB", target: "q-bio.QM", value: 364 },
        { source: "cs.LO", target: "cs.SC", value: 370 },
        { source: "physics.atm-clus", target: "physics.comp-ph", value: 396 },
        { source: "stat.ME", target: "stat.OT", value: 412 },
        { source: "physics.pop-ph", target: "physics.soc-ph", value: 414 },
        { source: "funct-an", target: "math.OA", value: 434 },
        { source: "comp-gas", target: "nlin.CG", value: 442 },
        { source: "q-fin.TR", target: "q-fin.ST", value: 446 },
        { source: "q-bio.TO", target: "q-bio.QM", value: 448 },
        { source: "physics.class-ph", target: "physics.ed-ph", value: 450 },
        { source: "q-fin.MF", target: "q-fin.PR", value: 472 },
        { source: "math.HO", target: "math.NT", value: 526 },
        { source: "nucl-ex", target: "physics.atom-ph", value: 536 },
        { source: "q-bio.SC", target: "cond-mat.stat-mech", value: 542 },
        { source: "cs.SC", target: "math.AG", value: 552 },
        { source: "physics.ed-ph", target: "physics.pop-ph", value: 558 },
        { source: "physics.hist-ph", target: "physics.pop-ph", value: 568 },
        { source: "cs.NI", target: "cs.MM", value: 576 },
        { source: "cs.ET", target: "cs.NE", value: 588 },
        { source: "q-bio.MN", target: "cond-mat.stat-mech", value: 646 },
        { source: "q-fin.ST", target: "physics.data-an", value: 654 },
        { source: "q-fin.PM", target: "math.OC", value: 658 },
        { source: "cs.FL", target: "cs.DM", value: 686 },
        { source: "math.NA", target: "cs.MS", value: 688 },
        { source: "chao-dyn", target: "cond-mat", value: 732 },
        { source: "econ.EM", target: "stat.ML", value: 734 },
        { source: "math.PR", target: "q-fin.CP", value: 758 },
        { source: "hep-th", target: "physics.gen-ph", value: 794 },
        { source: "cs.MS", target: "cs.NA", value: 818 },
        { source: "cond-mat.stat-mech", target: "q-bio", value: 874 },
        { source: "math.FA", target: "math.GN", value: 882 },
        { source: "physics.bio-ph", target: "q-bio.TO", value: 902 },
        { source: "cs.GT", target: "econ.TH", value: 918 },
        { source: "math.KT", target: "math.RA", value: 944 },
        { source: "cs.SE", target: "cs.DC", value: 1002 },
        { source: "cs.CV", target: "cs.SD", value: 1026 },
        { source: "q-bio.GN", target: "q-bio.QM", value: 1036 },
        { source: "q-bio.BM", target: "cond-mat.stat-mech", value: 1084 },
        { source: "cs.LG", target: "cs.AR", value: 1104 },
        { source: "physics.gen-ph", target: "physics.class-ph", value: 1110 },
        { source: "math.PR", target: "q-fin.MF", value: 1110 },
        { source: "cs.CG", target: "cs.DM", value: 1114 },
        { source: "q-bio.QM", target: "q-bio.MN", value: 1140 },
        { source: "adap-org", target: "nlin.AO", value: 1166 },
        { source: "cs.LG", target: "cs.CE", value: 1178 },
        { source: "cs.IR", target: "cs.DL", value: 1216 },
        { source: "quant-ph", target: "cs.ET", value: 1222 },
        { source: "physics.soc-ph", target: "stat.AP", value: 1254 },
        { source: "cs.PF", target: "cs.NI", value: 1256 },
        { source: "math.GN", target: "math.LO", value: 1282 },
        { source: "nlin.PS", target: "patt-sol", value: 1300 },
        { source: "physics.geo-ph", target: "astro-ph.EP", value: 1312 },
        { source: "cs.CE", target: "math.NA", value: 1314 },
        { source: "q-fin.GN", target: "physics.soc-ph", value: 1328 },
        { source: "stat.ME", target: "econ.EM", value: 1340 },
        { source: "physics.bio-ph", target: "physics.med-ph", value: 1350 },
        { source: "stat.AP", target: "stat.TH", value: 1382 },
        { source: "cs.GR", target: "cs.LG", value: 1400 },
        { source: "physics.bio-ph", target: "q-bio.SC", value: 1412 },
        { source: "physics.bio-ph", target: "q-bio.CB", value: 1438 },
        { source: "dg-ga", target: "math.DG", value: 1462 },
        { source: "physics.ao-ph", target: "physics.geo-ph", value: 1508 },
        { source: "physics.acc-ph", target: "physics.plasm-ph", value: 1520 },
        { source: "eess.AS", target: "stat.ML", value: 1534 },
        { source: "cs.DL", target: "physics.soc-ph", value: 1556 },
        { source: "cs.AI", target: "cs.DB", value: 1572 },
        { source: "cs.DB", target: "cs.LG", value: 1600 },
        { source: "physics.med-ph", target: "eess.IV", value: 1604 },
        { source: "physics.chem-ph", target: "physics.atm-clus", value: 1646 },
        { source: "cs.HC", target: "cs.RO", value: 1766 },
        { source: "cond-mat.quant-gas", target: "cond-mat.supr-con", value: 1776 },
        { source: "q-bio.NC", target: "cs.LG", value: 1788 },
        { source: "cmp-lg", target: "cs.CL", value: 1788 },
        { source: "math.CT", target: "math.RT", value: 1798 },
        { source: "cs.PL", target: "cs.SE", value: 1870 },
        { source: "eess.IV", target: "stat.ML", value: 1890 },
        { source: "cs.DS", target: "cs.CG", value: 1924 },
        { source: "cs.LG", target: "cs.GT", value: 1934 },
        { source: "cs.DC", target: "cs.PF", value: 1960 },
        { source: "cond-mat.other", target: "cond-mat.stat-mech", value: 2000 },
        { source: "cs.LO", target: "cs.FL", value: 2004 },
        { source: "math.GR", target: "math.DS", value: 2036 },
        { source: "quant-ph", target: "physics.hist-ph", value: 2074 },
        { source: "math.IT", target: "math.PR", value: 2086 },
        { source: "cond-mat.stat-mech", target: "q-bio.PE", value: 2182 },
        { source: "cs.SY", target: "eess.SP", value: 2298 },
        { source: "quant-ph", target: "cs.CC", value: 2312 },
        { source: "nlin.AO", target: "physics.soc-ph", value: 2342 },
        { source: "nlin.CD", target: "math.DS", value: 2604 },
        { source: "physics.optics", target: "nlin.PS", value: 2766 },
        { source: "math.AT", target: "math.KT", value: 2766 },
        { source: "math.GT", target: "math.SG", value: 2792 },
        { source: "cs.CR", target: "cs.NI", value: 2890 },
        { source: "math.LO", target: "cs.LO", value: 2956 },
        { source: "physics.bio-ph", target: "q-bio.BM", value: 3014 },
        { source: "stat.CO", target: "stat.ML", value: 3046 },
        { source: "math.QA", target: "q-alg", value: 3146 },
        { source: "math.AT", target: "math.CT", value: 3160 },
        { source: "math.RA", target: "math.QA", value: 3170 },
        { source: "cs.AI", target: "cs.MA", value: 3176 },
        { source: "math.CO", target: "math.MG", value: 3190 },
        { source: "physics.plasm-ph", target: "physics.space-ph", value: 3228 },
        { source: "physics.data-an", target: "physics.soc-ph", value: 3278 },
        { source: "cs.LO", target: "cs.PL", value: 3292 },
        { source: "cs.MM", target: "cs.CV", value: 3378 },
        { source: "cs.LG", target: "cs.HC", value: 3484 },
        { source: "cs.CV", target: "cs.GR", value: 3504 },
        { source: "q-bio.PE", target: "physics.soc-ph", value: 3596 },
        { source: "astro-ph.IM", target: "physics.ins-det", value: 3598 },
        { source: "cs.CY", target: "cs.SI", value: 3620 },
        { source: "math.AP", target: "math.CA", value: 3626 },
        { source: "math.CO", target: "math.AC", value: 3714 },
        { source: "math.GT", target: "math.AT", value: 3722 },
        { source: "math.SP", target: "math.AP", value: 3776 },
        { source: "cond-mat.str-el", target: "cond-mat.dis-nn", value: 3804 },
        { source: "math.CV", target: "math.DG", value: 4060 },
        { source: "cs.CC", target: "cs.DS", value: 4078 },
        { source: "cond-mat.stat-mech", target: "physics.bio-ph", value: 4156 },
        { source: "math.CA", target: "math.FA", value: 4204 },
        { source: "math.SG", target: "math.DG", value: 4262 },
        { source: "cs.LG", target: "cs.CY", value: 4270 },
        { source: "math.DG", target: "math.GT", value: 4312 },
        { source: "math.AG", target: "math.CV", value: 4382 },
        { source: "physics.atom-ph", target: "physics.optics", value: 4542 },
        { source: "stat.ME", target: "stat.CO", value: 4578 },
        { source: "physics.flu-dyn", target: "physics.comp-ph", value: 4708 },
        { source: "cs.NI", target: "cs.IT", value: 4732 },
        { source: "quant-ph", target: "cond-mat.other", value: 4752 },
        { source: "physics.comp-ph", target: "physics.chem-ph", value: 4814 },
        { source: "math.DS", target: "math.MP", value: 4816 },
        { source: "cs.RO", target: "cs.SY", value: 4976 },
        { source: "cs.DM", target: "cs.DS", value: 5014 },
        { source: "cs.NE", target: "cs.AI", value: 5072 },
        { source: "econ.GN", target: "q-fin.EC", value: 5154 },
        { source: "nlin.SI", target: "hep-th", value: 5410 },
        { source: "math.GT", target: "math.GR", value: 5436 },
        { source: "math.RT", target: "math.RA", value: 5460 },
        { source: "math.OC", target: "eess.SY", value: 5464 },
        { source: "cond-mat.soft", target: "physics.flu-dyn", value: 5802 },
        { source: "math.OA", target: "math.FA", value: 6040 },
        { source: "math.PR", target: "math.ST", value: 6108 },
        { source: "astro-ph.HE", target: "astro-ph.IM", value: 6220 },
        { source: "math.MP", target: "math.SP", value: 6264 },
        { source: "physics.app-ph", target: "physics.optics", value: 6600 },
        { source: "math.ST", target: "stat.ME", value: 6734 },
        { source: "cond-mat.mtrl-sci", target: "physics.app-ph", value: 6856 },
        { source: "math.AC", target: "math.AG", value: 7108 },
        { source: "math.NT", target: "math.CO", value: 7348 },
        { source: "cs.LG", target: "cs.IR", value: 7610 },
        { source: "eess.SP", target: "math.IT", value: 8148 },
        { source: "math.MP", target: "nlin.SI", value: 10020 },
        { source: "cs.LG", target: "cs.CR", value: 10094 },
        { source: "physics.ins-det", target: "hep-ex", value: 10914 },
        { source: "cond-mat.supr-con", target: "cond-mat.mes-hall", value: 11320 },
        { source: "hep-ex", target: "nucl-ex", value: 12198 },
        { source: "astro-ph.GA", target: "astro-ph.HE", value: 12440 },
        { source: "quant-ph", target: "cond-mat.quant-gas", value: 12458 },
        { source: "hep-lat", target: "hep-th", value: 12522 },
        { source: "cs.SI", target: "physics.soc-ph", value: 13650 },
        { source: "astro-ph.EP", target: "astro-ph.SR", value: 13776 },
        { source: "cond-mat.dis-nn", target: "cond-mat.stat-mech", value: 14142 },
        { source: "cs.SD", target: "eess.AS", value: 15730 },
        { source: "cond-mat.stat-mech", target: "cond-mat.soft", value: 18306 },
        { source: "gr-qc", target: "astro-ph", value: 18504 },
        { source: "cs.CL", target: "cs.LG", value: 19306 },
        { source: "astro-ph.SR", target: "astro-ph.GA", value: 19534 },
        { source: "nucl-th", target: "nucl-ex", value: 20534 },
        { source: "hep-ph", target: "hep-lat", value: 20808 },
        { source: "cond-mat.mes-hall", target: "quant-ph", value: 21760 },
        { source: "gr-qc", target: "hep-ph", value: 24094 },
        { source: "hep-ph", target: "astro-ph.CO", value: 24442 },
        { source: "cond-mat.supr-con", target: "cond-mat.str-el", value: 24746 },
        { source: "eess.SY", target: "cs.SY", value: 27550 },
        { source: "cs.NA", target: "math.NA", value: 28654 },
        { source: "astro-ph.CO", target: "gr-qc", value: 29382 },
        { source: "cond-mat.mes-hall", target: "cond-mat.mtrl-sci", value: 30460 },
        { source: "hep-th", target: "math-ph", value: 32448 },
        { source: "hep-ph", target: "nucl-th", value: 47362 },
        { source: "cs.IT", target: "math.IT", value: 80342 },
    ],
};
